apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4K
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQK
---
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: mongodb-standalone
    spec:
      serviceName: database
      replicas: 1
      selector:
        matchLabels:
          app: database
      template:
        metadata:
          labels:
            app: database
            selector: mongodb-standalone
        spec:
          containers:
          - name: mongodb-standalone
            image: mongo:4.0.8
            env:
              - name: MONGO_INITDB_ROOT_USERNAME_FILE
                value: /etc/blog-secrets/admin/MONGO_ROOT_USERNAME
              - name: MONGO_INITDB_ROOT_PASSWORD_FILE
                value: /etc/blog-secrets/admin/MONGO_ROOT_PASSWORD
            volumeMounts:
            - name: blog-secrets
              mountPath: /etc/blog-secrets
              readOnly: true
          volumes:
          - name: blog-secrets
            secret:
              secretName: blog-secrets
              items:
              - key: MONGO_ROOT_USERNAME
                path: admin/MONGO_ROOT_USERNAME
                mode: 0444
              - key: MONGO_ROOT_PASSWORD
                path: admin/MONGO_ROOT_PASSWORD
                mode: 0444
---
    apiVersion: v1
    kind: Service
    metadata:
      name: database
      labels:
        app: database
    spec:
      clusterIP: None
      selector:
        app: database